version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-type: "direct"
    open-pull-requests-limit: 20
